samantha_root = "E:/Samantha"
project_name = "BirdBook"
ask_name = "True"
ask_username = "True"
ask_email = "True"
ask_phone = "True"
ask_pronouns = "True"
ask_gender = "True"
ask_birthday = "True"
ask_others = "Age, Favorite Color, Address"
old_username_redirect = "True"
complete_deleting_delay = "30"
